# Generated by Django 5.0 on 2024-03-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_credits_course_credit_course_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='credits',
        ),
    ]
