# Generated by Django 5.0 on 2024-03-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_credit_course_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='course_credits',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='year',
            new_name='course_year',
        ),
    ]
