# Generated by Django 5.0 on 2024-03-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_credits_course_course_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_year',
        ),
    ]
