# Generated by Django 5.0 on 2024-06-02 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_timetable_courseschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_range',
            field=models.CharField(choices=[('08:00-11:00', '08:00-11:00'), ('11:00-14:00', '11:00-14:00'), ('14:00-17:00', '14:00-17:00')], default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
