# Generated by Django 5.0 on 2024-03-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_course_course_credits_course_course_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_credits',
            new_name='course_credit',
        ),
    ]
