# Generated by Django 5.0 on 2024-06-17 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_timeslot_end_time_remove_timeslot_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
