# Generated by Django 5.0 on 2024-03-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_course_credits_course_course_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_credit',
            new_name='course_credits',
        ),
    ]
