# Generated by Django 5.0 on 2024-03-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_course_credit_course_course_credits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
