# Generated by Django 5.0.7 on 2024-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_course_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
