# Generated by Django 5.0 on 2024-03-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
